# Generated by Django 4.2.1 on 2023-05-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_item',
            field=models.CharField(default='https://cdn.kuali.com/wp-content/uploads/2021/06/01224825/840x560-Prawn-Arrabiata-Spaghetti.jpg', max_length=500),
        ),
    ]
