# Generated by Django 4.2.1 on 2023-05-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_image_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image_item',
            new_name='item_image',
        ),
    ]
